CREATE TABLE cliente (
	wallet	 NUMERIC(10, 2),
	nif	 VARCHAR(512),
	telefone	 VARCHAR(512),
	pessoa_id BIGINT,
	PRIMARY KEY(pessoa_id)
);

CREATE TABLE pessoa (
	id		 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome		 VARCHAR(512),
	email	 VARCHAR(512),
	username	 VARCHAR(512),
	password_hash VARCHAR(512),
	PRIMARY KEY(id)
);

CREATE TABLE administrador (
	is_super	 BOOL,
	pessoa_id BIGINT,
	PRIMARY KEY(pessoa_id)
);

CREATE TABLE trajeto (
	sequencia			 INTEGER,
	tempo_previsto_desde_origem INTEGER,
	distancia_acumulada	 FLOAT(8),
	plataforma_sentido		 VARCHAR(512) CHECK (plataforma_sentido IN ('A', 'B')),
	linha_id			 BIGINT,
	paragem_id			 BIGINT NOT NULL,
	PRIMARY KEY(sequencia, linha_id, plataforma_sentido)
);

CREATE TABLE linha (
	id		 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome		 VARCHAR(512),
	hora_inicio	 VARCHAR(512),
	hora_fim		 VARCHAR(512),
	frequencia	 INTEGER,
	capacidade_default INTEGER,
	PRIMARY KEY(id)
);

CREATE TABLE paragem (
	id	 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(512),
	PRIMARY KEY(id)
);

CREATE TABLE viagem (
	id			 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	data_hora_partida	 TIMESTAMP,
	direcao		 VARCHAR(512),
	capacidade_disponivel BIGINT CHECK (capacidade_disponivel >= 0),
	atraso_estimado	 BIGINT,
	linha_id		 BIGINT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE tipo_bilhete (
	id_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nome	 VARCHAR(512),
	PRIMARY KEY(id_tipo)
);

CREATE TABLE bilhete (
	id			 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	data_compra		 DATE,
	preco_compra	 NUMERIC(10, 2),
	data_inicio_validade DATE,
	data_fim_validade	 DATE,
	data_viagem		 DATE,
	data_expiracao	 DATE,
	estado		 VARCHAR(512),
	metodo_pagamento	 VARCHAR(512),
	desconto_aplicado	 INTEGER,
	tipo_bilhete_id_tipo BIGINT NOT NULL,
	cliente_pessoa_id	 BIGINT NOT NULL,
	linha_id		 BIGINT,
	PRIMARY KEY(id)
);

CREATE TABLE validacao (
	data_hora	 TIMESTAMP,
	bilhete_id BIGINT,
	viagem_id	 BIGINT,
	paragem_id BIGINT NOT NULL,
	PRIMARY KEY(bilhete_id,viagem_id)
);

CREATE TABLE promocao (
	id_promocao		 INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome		 VARCHAR(512),
	desconto		 INTEGER,
	data_inicio		 DATE,
	data_fim		 DATE,
	tipo_bilhete_id_tipo BIGINT NOT NULL,
	linha_id		 BIGINT NOT NULL,
	PRIMARY KEY(id_promocao)
);

CREATE TABLE aviso (
	id			 BIGINT GENERATED BY DEFAULT AS IDENTITY,
	titulo			 VARCHAR(512),
	mensagem		 VARCHAR(512),
	data_emissao		 DATE,
	administrador_pessoa_id BIGINT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE carregamento (
	id_carregamento	 INTEGER GENERATED BY DEFAULT AS IDENTITY,
	valor		 NUMERIC(10, 2),
	metodo_pagamento	 VARCHAR(512),
	data_hora	 TIMESTAMP,
	cliente_pessoa_id BIGINT NOT NULL,
	PRIMARY KEY(id_carregamento)
);

CREATE TABLE historico_preco (
	preco		 NUMERIC(10, 2),
	data_efetiva	 DATE,
	tipo_bilhete_id_tipo BIGINT,
	PRIMARY KEY(data_efetiva,tipo_bilhete_id_tipo)
);

CREATE TABLE aviso_cliente (
	data_entrega	 DATE,
	data_leitura	 DATE,
	lido		 BOOL,
	aviso_id		 BIGINT,
	cliente_pessoa_id BIGINT,
	PRIMARY KEY(aviso_id,cliente_pessoa_id)
);

CREATE TABLE interrupcao_linha (
	id_interrupcao		 INTEGER GENERATED BY DEFAULT AS IDENTITY,
	data_inicio		 DATE,
	data_fim		 DATE,
	motivo			 VARCHAR(512),
	estado			 BOOL,
	administrador_pessoa_id BIGINT NOT NULL,
	linha_id		 BIGINT NOT NULL,
	PRIMARY KEY(id_interrupcao)
);

ALTER TABLE cliente ADD CONSTRAINT cliente_fk1 FOREIGN KEY (pessoa_id) REFERENCES pessoa(id);
ALTER TABLE pessoa ADD UNIQUE (email);
ALTER TABLE pessoa ADD UNIQUE (username);
ALTER TABLE administrador ADD CONSTRAINT administrador_fk1 FOREIGN KEY (pessoa_id) REFERENCES pessoa(id);
ALTER TABLE trajeto ADD CONSTRAINT trajeto_fk1 FOREIGN KEY (linha_id) REFERENCES linha(id);
ALTER TABLE trajeto ADD CONSTRAINT trajeto_fk2 FOREIGN KEY (paragem_id) REFERENCES paragem(id);
ALTER TABLE viagem ADD CONSTRAINT viagem_fk1 FOREIGN KEY (linha_id) REFERENCES linha(id);
ALTER TABLE bilhete ADD CONSTRAINT bilhete_fk1 FOREIGN KEY (tipo_bilhete_id_tipo) REFERENCES tipo_bilhete(id_tipo);
ALTER TABLE bilhete ADD CONSTRAINT bilhete_fk2 FOREIGN KEY (cliente_pessoa_id) REFERENCES cliente(pessoa_id);
ALTER TABLE bilhete ADD CONSTRAINT bilhete_fk3 FOREIGN KEY (linha_id) REFERENCES linha(id);
ALTER TABLE validacao ADD CONSTRAINT validacao_fk1 FOREIGN KEY (bilhete_id) REFERENCES bilhete(id);
ALTER TABLE validacao ADD CONSTRAINT validacao_fk2 FOREIGN KEY (viagem_id) REFERENCES viagem(id);
ALTER TABLE validacao ADD CONSTRAINT validacao_fk3 FOREIGN KEY (paragem_id) REFERENCES paragem(id);
ALTER TABLE promocao ADD CONSTRAINT promocao_fk1 FOREIGN KEY (tipo_bilhete_id_tipo) REFERENCES tipo_bilhete(id_tipo);
ALTER TABLE promocao ADD CONSTRAINT promocao_fk2 FOREIGN KEY (linha_id) REFERENCES linha(id);
ALTER TABLE aviso ADD CONSTRAINT aviso_fk1 FOREIGN KEY (administrador_pessoa_id) REFERENCES administrador(pessoa_id);
ALTER TABLE carregamento ADD CONSTRAINT carregamento_fk1 FOREIGN KEY (cliente_pessoa_id) REFERENCES cliente(pessoa_id);
ALTER TABLE historico_preco ADD CONSTRAINT historico_preco_fk1 FOREIGN KEY (tipo_bilhete_id_tipo) REFERENCES tipo_bilhete(id_tipo);
ALTER TABLE aviso_cliente ADD CONSTRAINT aviso_cliente_fk1 FOREIGN KEY (aviso_id) REFERENCES aviso(id);
ALTER TABLE aviso_cliente ADD CONSTRAINT aviso_cliente_fk2 FOREIGN KEY (cliente_pessoa_id) REFERENCES cliente(pessoa_id);
ALTER TABLE interrupcao_linha ADD CONSTRAINT interrupcao_linha_fk1 FOREIGN KEY (administrador_pessoa_id) REFERENCES administrador(pessoa_id);
ALTER TABLE interrupcao_linha ADD CONSTRAINT interrupcao_linha_fk2 FOREIGN KEY (linha_id) REFERENCES linha(id);

CREATE OR REPLACE FUNCTION trigger_deduct_wallet_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.metodo_pagamento = 'wallet' THEN
        UPDATE cliente
        SET wallet = wallet - NEW.preco_compra
        WHERE pessoa_id = NEW.cliente_pessoa_id AND wallet >= NEW.preco_compra;
        
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Saldo insuficiente na carteira ou cliente inexistente';
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_deduct_wallet
BEFORE INSERT ON bilhete
FOR EACH ROW
EXECUTE FUNCTION trigger_deduct_wallet_func();

-- B-Tree Indexes on Foreign Keys (Performance Optimization)
CREATE INDEX idx_trajeto_linha ON trajeto(linha_id);
CREATE INDEX idx_trajeto_paragem ON trajeto(paragem_id);
CREATE INDEX idx_viagem_linha ON viagem(linha_id);
CREATE INDEX idx_bilhete_tipo_bilhete ON bilhete(tipo_bilhete_id_tipo);
CREATE INDEX idx_bilhete_cliente ON bilhete(cliente_pessoa_id);
CREATE INDEX idx_bilhete_linha ON bilhete(linha_id);
CREATE INDEX idx_validacao_viagem ON validacao(viagem_id);
CREATE INDEX idx_validacao_paragem ON validacao(paragem_id);
CREATE INDEX idx_promocao_tipo_bilhete ON promocao(tipo_bilhete_id_tipo);
CREATE INDEX idx_promocao_linha ON promocao(linha_id);
CREATE INDEX idx_aviso_admin ON aviso(administrador_pessoa_id);
CREATE INDEX idx_carregamento_cliente ON carregamento(cliente_pessoa_id);
CREATE INDEX idx_historico_preco_tipo_bilhete ON historico_preco(tipo_bilhete_id_tipo);
CREATE INDEX idx_aviso_cliente_pessoa ON aviso_cliente(cliente_pessoa_id);
CREATE INDEX idx_interrupcao_linha_admin ON interrupcao_linha(administrador_pessoa_id);
CREATE INDEX idx_interrupcao_linha_linha ON interrupcao_linha(linha_id);